Support dynamic updating of history and use deltas for import

diff --git a/archelonc/scripts/archelon b/archelonc/scripts/archelon
--- a/archelonc/scripts/archelon
+++ b/archelonc/scripts/archelon
@@ -3,7 +3,13 @@
 # source in rather than execute. i.e. `. archelon`. This
 # will run the python interface and interactively drop the command
 # entered
+
+# Dump history and update server with latest if configured
 history -a
+archelon_update
+if [ $? -ne 0 ]; then
+	echo "Server update failed, check configuration/server."
+fi
 
 archelonf
 rc=$?
